# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af40b41785e8ae3924b3d30b4307f0751cb85f339b8e8ab6101862a2538540f518b366ee11afd5d13064ecb684503fe10a2952ce11fd8c99ba63a70c8ce4a9ab

test:
  secret_key_base: 4ba5816c271d39373601141aca0a3930f17d2101e11981107e7f97e65a6da2b36d7164ca8fdcffaf0dfa1a040a107e183cd3e79391835df6300fab93ebd06db6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
